version: "3.9"
services:
  shopbr-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - shopbr-db:/app/database
      - shopbr-models:/app/models
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  shopbr-db:
  shopbr-models:
